### ISSUE TITLE
Payment guards?

### ISSUE THREAD

**Issue by KrishnaPG** [interledgerjs/ilp#139]
May be I am missing something, but the documentation does not seem to cover one important aspect:

- what is preventing someone to call the `pay` method in a loop 10000 times to send money that does not exist?

Is the API going to check some balance / wallet before making the transfer? if So, where and how? The example code (copied below from the readme), does not seem to indicate any source wallet address
````
await ilp.pay(100, '$bob.example.com')
````

I understand this is just an API, but if the API does what it says (namely making the payment), the receiver would endup with that `100` amount irrespective of caller has it or not.  Currently all banks use one or the other form of API, but they all are tied to some user account and need valid credentials - which does not seem to be the case in these ILP APIs.

**Comment by emschwartz** [comment]
Hi @KrishnaPG, that code connects to [`moneyd`](https://github.com/interledgerjs/moneyd), which manages an account with some connector. If you send more than you have, the connector will reject those packets. The source address is also determined by `moneyd`.

Regarding authentication, `moneyd` uses authentication to connect to the connector. Right now apps generate tokens to connect to `moneyd` but it allows any connections so it needs more controls to prevent rogue apps on your machine from spending money freely.
