### ISSUE TITLE
Add SPSP client

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp#39]
Currently, the `ilp` module implements [IPR](https://github.com/interledger/rfcs/blob/master/0011-interledger-payment-request/0011-interledger-payment-request.md), but not [SPSP](https://github.com/interledger/rfcs/blob/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md).

Part of the reason was that the server-side of SPSP is very simple and there are many server-side frameworks, so you'd end up with a module that doesn't do very much and needs tons of glue for different use cases.

However, the story is different for the client side. There is a bit more logic involved and the flows are more standardized. (While a server might be _only_ a merchant or _only_ a payee, clients have to handle all SPSP responses pretty much the same way.)

So I think we should have a module that implements SPSP client-side functionality. Question is whether this should be in `ilp` or in a separate module `spsp`. (Leaning towards the latter, but input is welcome.)

**Comment by gGololicic** [comment]
Stumbled here because I was wondering about the same question. I think it would be helpful to have an spsp module.

**Comment by emschwartz** [comment]
I'm thinking we might want to set the `ilp` module up kind of like how `lodash` is set up. We could have an `ilp-spsp-client` module, an `ilp-ipr` module, and bundle those and maybe the most common plugins (if their dependency trees aren't too crazy) into the `ilp` module.

In general I like the idea of the `ilp` module being the go-to module for most client use cases.

**Comment by emschwartz** [comment]
It is done
