### ISSUE TITLE
Simpler constructor

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp#60]
Currently the example is:

``` js
const sender = ILP.createSender({
  _plugin: FiveBellsLedgerPlugin,
  prefix: 'ilpdemo.red.',
  account: 'https://red.ilpdemo.org/ledger/accounts/alice',
  password: 'alice'
})
```

Could that be just:

``` js
const sender = ILP.createSender({
  account: 'alice@red.ilpdemo.org',
  password: 'alice'
})
```

* Use the same identifier as SPSP
* Detect prefix automatically
* Assume Five Bells Ledger as the default (not sure if this is a good idea, weigh in please!)

**Comment by emschwartz** [comment]
https://github.com/interledgerjs/ilp/pull/79 changes the API such that the sender must instantiate the plugin first, instead of having the ILP module do it. We _could_ implement this in the `ilp-plugin-bells`, but I'm not sure that's a good idea
